/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated/programs'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlacementsRouteImport } from './routes/_authenticated/placements'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedExaminationsRouteImport } from './routes/_authenticated/examinations'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAcademicsRouteImport } from './routes/_authenticated/academics'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students/new'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacementsRoute = AuthenticatedPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminationsRoute =
  AuthenticatedExaminationsRouteImport.update({
    id: '/examinations',
    path: '/examinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicsRoute = AuthenticatedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/academics': typeof AuthenticatedAcademicsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/examinations': typeof AuthenticatedExaminationsRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/placements': typeof AuthenticatedPlacementsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/academics'
    | '/attendance'
    | '/audit'
    | '/communications'
    | '/dashboard'
    | '/departments'
    | '/examinations'
    | '/fees'
    | '/library'
    | '/placements'
    | '/profile'
    | '/programs'
    | '/students/$id'
    | '/students/new'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/academics'
    | '/attendance'
    | '/audit'
    | '/communications'
    | '/dashboard'
    | '/departments'
    | '/examinations'
    | '/fees'
    | '/library'
    | '/placements'
    | '/profile'
    | '/programs'
    | '/students/$id'
    | '/students/new'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/academics'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/communications'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/examinations'
    | '/_authenticated/fees'
    | '/_authenticated/library'
    | '/_authenticated/placements'
    | '/_authenticated/profile'
    | '/_authenticated/programs'
    | '/_authenticated/students/$id'
    | '/_authenticated/students/new'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placements': {
      id: '/_authenticated/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AuthenticatedPlacementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations': {
      id: '/_authenticated/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof AuthenticatedExaminationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics': {
      id: '/_authenticated/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AuthenticatedAcademicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicsRoute: typeof AuthenticatedAcademicsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedExaminationsRoute: typeof AuthenticatedExaminationsRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPlacementsRoute: typeof AuthenticatedPlacementsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicsRoute: AuthenticatedAcademicsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedExaminationsRoute: AuthenticatedExaminationsRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPlacementsRoute: AuthenticatedPlacementsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
